version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: task-rabbitmq
    restart: always
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
